# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SUDDA
email: support@sudda.info
description: > # this means to ignore newlines until "baseurl:"
  Sudda management solution for small businesses, support for mobile and tablets.
  
  
url: "http://sudda.info" # the base hostname & protocol for your site
# twitter_username: sudda
# github_username:  sudda
# baseurl: "" # the subpath of your site, e.g. /blog
# Build settings
markdown: kramdown
